name: Simular Commits periódicos

on:
  schedule:
    - cron: '*/15 * * * *'  # De 15 em 15 minutos
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repositório
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          token: ${{ secrets.GH_PAT }}  # seu token personalizado aqui
      - name: Criar commit simulado
        run: |
          echo "Commit simulado em $(date)" >> simulacao.txt
          git config user.name "simulador-in"
          git config user.email "simulador@in1.com"
          git add simulacao.txt
          git commit -m "feat: commit simulado automático em $(date)"
          git push origin main
