name: Simular incidentes (MTTR e Failure Rate)

on:
  schedule:
    - cron: '0 * * * *'  #de hora em hora  #'*/15 * * * *'  # De 15 em 15 minutos
  workflow_dispatch:

jobs:
  incidente:
    runs-on: ubuntu-latest
    steps:
      - name: Criar incidente simulado
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          REPO: ${{ github.repository }}
        run: |
          echo "Criando issue..."
          CREATED_ISSUE=$(curl -s -X POST https://api.github.com/repos/$REPO/issues \
            -H "Authorization: token $GH_PAT" \
            -H "Accept: application/vnd.github+json" \
            -d '{
              "title": "🚨 Incidente simulado em Produção",
              "body": "Falha simulada gerada automaticamente pelo GitHub Actions.",
              "labels": ["incident", "production"]
            }')

          ISSUE_NUMBER=$(echo "$CREATED_ISSUE" | jq '.number')
          echo "Issue criada: #$ISSUE_NUMBER"

          echo "Aguardando 1 minuto antes de fechar (simulando restauração)..."
          sleep 60

          echo "Fechando issue #$ISSUE_NUMBER..."
          curl -s -X PATCH https://api.github.com/repos/$REPO/issues/$ISSUE_NUMBER \
            -H "Authorization: token $GH_PAT" \
            -H "Accept: application/vnd.github+json" \
            -d '{"state": "closed"}'

          echo "Issue fechada com sucesso."
