name: Simular incidentes (MTTR e Failure Rate)

on:
  schedule:
    - cron: '*/15 * * * *'  # De 15 em 15 minutos
  workflow_dispatch:

jobs:
  incidente:
    runs-on: ubuntu-latest
    steps:
      - name: Criar incidente simulado
        uses: actions/github-script@v6
        with:
          script: |
            const issue = await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: '🚨 Incidente simulado em Produção',
              body: 'Falha simulada gerada automaticamente pelo GitHub Actions.',
              labels: ['incident', 'production']
            });
            
            console.log(`Incidente criado: ${issue.data.number}`);

            // Fecha automaticamente a issue após 1 hora (simulando restauração rápida)
            const wait = ms => new Promise(resolve => setTimeout(resolve, ms));
            await wait(3600000); // espera 1 hora (3600s)

            await github.rest.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue.data.number,
              state: 'closed'
            });
            
            console.log(`Incidente resolvido: ${issue.data.number}`);
